language: shell
os: linux

services:
- docker

before_install:
- docker pull centos:7.5.1804
- docker pull centos:7.6.1810
- docker pull centos:7.7.1908

env:
 global:
   - KUBE_VERSION=1.17.0
 
script:
  - bash -x scripts/get_packages.sh
  - docker build -t willdockerhub/kubeansible:v$KUBE_VERSION .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push willdockerhub/kubeansible:v$KUBE_VERSION