sudo: required

services:
- docker

before_install:
- docker pull centos:7.5.1804
- docker pull centos:7.6.1810
- docker pull centos:7.7.1908

env:
 global:
   - KUBE_VERSION=1.17.0
 
jobs:
  include:
    - stage: build yum repo rpm packages
      script:
      - sh yum-repo/build_yum_repo.sh

    - stage: get docker image and other files
      script:
      - sh scripts/get_packages.sh

    - stage: build kubeansible image
      script:
      - docker build -t willdockerhub/kubeansible:$KUBE_VERSION .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push willdockerhub/kubeansible:$KUBE_VERSION
