---
- hosts: all
  gather_facts: no
  roles:
    - auth
---
- hosts: all
  gather_facts: yes
  roles:
    - docker
---
- hosts: registry
  gather_facts: no
  roles:
    - harbor
- hosts: 
  - lb
  roles:
    - cluster
- hosts: etcd
  gather_facts: no
  roles:
    - etcd
- hosts: 
    - master
    - node
  gather_facts: yes
  roles:
    - kubernetes
