- name: make lb dir
  file: 
    name={{ item }} 
        state=directory
        mode: 0755
  with_items:
    - /var/lib/loadbalancer

- name: generate lb config
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'templates/haproxy.cfg.j2', dest: '/var/lib/loadbalancer/haproxy.cfg' }
    - { src: 'templates/keepalive.cfg.j2', dest: '/var/lib/loadbalancer/keepalive.cfg' }

- name: copy keepalived script
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'file/keepalived.sh', dest: '/var/lib/loadbalancer' }

- name: run haproxy
  docker_container:
    name: haproxy
    restart_policy: unless-stopped
    image: "willdockerhub/haproxy-k8s:latest"
    ports: '6444'
    volumes:
    - '/var/lib/loadbalancer/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'

- name: run keepalived
  docker_container:
    name: keepalived
    network_mode: host
    restart_policy: unless-stopped
    capabilities: NET_ADMIN
    image: "willdockerhub/keepalived-k8s:latest"
    entrypoint: /bin/bash
    command: /usr/bin/keepalived.sh
    volumes:
    - '/var/lib/loadbalancer/keepalive.cfg:/etc/keepalived/keepalived.conf'
    - '/var/lib/loadbalancer/keepalived.sh:/usr/bin/keepalived.sh'
