- name: clear auth
  vars:
    ansible_python_interpreter: /usr/bin/python3
  lineinfile:
    path: /root/.ssh/known_hosts
    state: absent
    regexp: '{{ hostvars[inventory_hostname].ansible_ssh_host }}'
  connection: local
  when: "inventory_hostname in groups['allnodes']"
