- name: remove docker for Redhat/CentOS
  yum:
    disablerepo: '*'
    enablerepo: wise2c
    state: absent
    name: '{{ item }}'
  with_items:
  - docker-ce
  - docker-compose
  when: "inventory_hostname in groups['allnodes']"
#  when: (ansible_distribution =="RedHat") or (ansible_distribution =="CentOS")

- name: remove docker for Ubuntu
  apt:
    state: absent
    name: '{{ item }}'
  with_items:
  - docker-ce
  - docker-compose
#  when: "inventory_hostname in groups['allnodes']"
  when: ansible_distribution =="Ubuntu"
