- name: make script dir
  file:
    path: '{{ DPATH }}'
    state: directory
  connection: local
  run_once: true

- name: distribute the script to host
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
    - { src: 'file/gen-rsa.sh', dest: '{{ DPATH }}' }
    - { src: 'file/get-public-key.sh', dest: '{{ DPATH }}' }
  connection: local
  run_once: true

- name: generate rsa and rsa.pub
  shell: '{{ DPATH }}/gen-rsa.sh'
  connection: local
  run_once: true

- name: get public key
  shell: '{{ DPATH }}/get-public-key.sh {{ inventory_hostname }}'
  connection: local

- name: install ssh key
  authorized_key: user=root
                  key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
                  state=present
