- name: copy calico.yaml and images
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - { src: '{{ base_dir }}/images/calico.tar.bz2', dest: '{{ dpath }}/' }
  - { src: '{{ base_dir }}/conf/calico.yaml', dest: '{{ dpath }}/' }
  run_once: true

- name: load calico images
  docker_image:
    load_path: '{{ dpath }}/calico.tar.bz2'
    name: calico
    timeout: 600
    source: load
  run_once: true

- name: replace pod cidr in calico yaml files
  replace:
    dest: "{{ item.filename }}"
    regexp: "192.168.0.0/16"
    replace: "{{ pod_cidr }}"
  with_items:
    - { filename: "{{ dpath }}/calico.yaml" }
  run_once: true

- name: add calico_node_ip_detection_mode in calico yaml files
  replace:
    dest: "{{ item.filename }}"
    regexp: '- name: FELIX_HEALTHENABLED[\S\s]*?value: "true"'
    replace: '- name: FELIX_HEALTHENABLED\n              value: "true"\n            - name: IP_AUTODETECTION_METHOD\n              value: {{ calico_node_ip_detection_mode }}'
  with_items:
  - { filename: '{{ dpath }}/calico.yaml' }
  run_once: true
  when: calico_node_ip_detection_mode
  
- name: Create calico cni
  k8s:
    state: present
    src: {{ dpath }}/calico/k8s-manifests/calico.yaml
