- name: copy kube-flannel.yaml and images
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - { src: '{{ base_dir }}/images/kube-flannel.tar.bz2', dest: '{{ dpath }}/' }
  - { src: '{{ base_dir }}/conf/kube-flannel.yml', dest: '{{ dpath }}/' }
  run_once: true

- name: load flannel images
  docker_image:
    load_path: '{{ dpath }}/kube-flannel.tar.bz2'
    name: flannel
    timeout: 600
    source: load
  run_once: true

- name: replace pod cird 10.244.0.0/16 in flannel yaml files
  replace:
    dest: "{{ item.filename }}"
    regexp: "10.244.0.0/16"
    replace: "{{ pod_cird }}"
  with_items:
    - { filename: "{{ dpath }}/kube-flannel.yml" }
  run_once: true

- name: apply flannel cni
  k8s:
    state: present
    src: {{ dpath }}/kube-flannel.yml
