- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['master'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- debug: var=kubeadm_join

- name: Store join command
  action: copy content="{{ kubeadm_join }}" dest="/etc/kubernetes/kubeadm-join.command"

- name: kubeadm join master node
  shell: "{{ kubeadm_join }} --control-plane"
  when: (inventory_hostname not in groups['master'][0]) and (inventory_hostname not in groups['node'])

- name: kubeadm join worker node
  shell: "{{ kubeadm_join }}"
  when: inventory_hostname in groups['node']
