- name: check kubernetes services
  script: scripts/check_kubelet_kubeproxy.sh
  register: check_output

- block:
  - name: init master and worker node
    include_tasks: prepare.yml

  - name: setup master nodes
    include_tasks: master-node.yml
    when: "inventory_hostname in groups['master']"

  - name: setup worker nodes
    include_tasks: worker-node.yml
    when: "inventory_hostname in groups['node']" 
  when: not (check_output.stdout == True)
