- name: check kubernetes services
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- block:
  - include_tasks: prepare.yml

  - include_tasks: master-init.yml
    when: 
    - inventory_hostname == groups['master'][0]

  - include_tasks: join-nodes.yml
        
  - include_tasks: calico.yml
    when: (inventory_hostname == groups['master'][0]) and (network_plugin == 'calico')

  - include_tasks: flannel.yml
    when: (inventory_hostname == groups['master'][0]) and (network_plugin == 'flannel')
  when: not kubelet_conf_stat.stat.exists
