- name: check kubernetes services
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- block:
  - name: prepare job
    include_tasks: prepare.yml

  - include_tasks: generate-certificates.yml
    when: 
    - inventory_hostname == groups['master'][0]

  - include_tasks: master-init.yml
    when: inventory_hostname == groups['master'][0]

  - include_tasks: master-join.yml
    when: (inventory_hostname not in groups['master'][0]) and (inventory_hostname not in groups['node'])

  - include_tasks: worker-join.yml
    when: inventory_hostname in groups['node']
 
  - include_tasks: calico.yml
    when: (inventory_hostname == groups['master'][0]) and (network_plugin == 'calico')

  - include_tasks: flannel.yml
    when: (inventory_hostname == groups['master'][0]) and (network_plugin == 'flannel')
  when: not kubelet_conf_stat.stat.exists
