- name: kubeadm init
  shell: |
    kubeadm init --config kubeadm.conf --upload-certs
  args:
    chdir: '{{ dpath }}/kubernetes/'
  register: kubeadm_init_result

- name: config kubectl
  shell: |
    cp /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: update kube-proxy HA setting
  shell: |
    kubectl -n kube-system get cm kube-proxy -o yaml > {{ dpath }}/kubernetes/kube-proxy-cm.yaml
    sed -i "s#.*server:.*#        server: https://{{ endpoint }}#g" {{ dpath }}/kubernetes/kube-proxy-cm.yaml
    kubectl -n kube-system apply -f {{ dpath }}/kubernetes/kube-proxy-cm.yaml

- name: Store kubeadm_init_result
  action: copy content="{{ kubeadm_init_result.stdout }}" dest="{{ dpath }}/kubernetes/kubeadm_init_result"

- name: save join command
  shell: |
    cat {{ dpath }}/kubernetes/kubeadm_init_result | grep '\-\-control-plane' -B2 > {{ dpath }}/kubernetes/kubeadm-join-master.command
    cat {{ dpath }}/kubernetes/kubeadm_init_result | tail -n2 > {{ dpath }}/kubernetes/kubeadm-join-worker.command

- name: fetch join command
  fetch:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    flat: true
  with_items:
  - { src: '{{ dpath }}/kubernetes/kubeadm-join-master.command', dest: 'files/kubeadm-join-master.command' }
  - { src: '{{ dpath }}/kubernetes/kubeadm-join-worker.command', dest: 'files/kubeadm-join-worker.command' }
