- name: make k8s dir
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
  - /etc/kubernetes/pki
  - '{{ dpath }}/kubernetes/'
  - $HOME/.kube

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Turn swap off
  shell: swapoff -a

- name: distribute ipvs bootload file
  template:
    src: ipvs.conf.j2
    dest: /etc/modules-load.d/ipvs.conf

- name: enable systemd-modules-load.service
  systemd:
    name: systemd-modules-load
    daemon_reload: true
    enabled: true
    state: restarted

- name: clean yum cache
  shell: |
    yum clean all
  args:
    warn: no  

- name: install kubernetes components for Redhat/CentOS
  yum:
    disablerepo: '*'
    enablerepo: kubeansible
    update_cache: true
    state: present
    name:
      - kubectl-{{ kubernetes_version[1:] }}
      - kubelet-{{ kubernetes_version[1:] }}
      - kubeadm-{{ kubernetes_version[1:] }}

- name: copy cfssl tool
  copy:
    src: '{{ item }}'
    dest: /usr/local/bin
    mode: '0755'
  with_items:
  - '{{ base_dir }}/bin/cfssl'
  - '{{ base_dir }}/bin/cfssljson'
  - '{{ base_dir }}/bin/cfssl-certinfo'
  run_once: true

- name: distribute kubelet config for Redhat/CentOS
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - { src: 'kubelet.conf.j2', dest: '/etc/sysconfig/kubelet' }

- name: reload and enable kubelet
  systemd:
    name: kubelet
    daemon_reload: true
    enabled: true

- name: copy k8s images
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - { src: '{{ base_dir }}/images/k8s.tar.bz2', dest: '{{ dpath }}/kubernetes' }
  run_once: true

- name: load k8s images
  docker_image:
    load_path: '{{ dpath }}/{{ item }}'
    name: k8s
    timeout: 600
    source: load
  with_items:
  - kubernetes/k8s.tar.bz2
  run_once: true
