- name: yum install docker
  yum:
    disablerepo: '*'
    enablerepo: kubeansible
    update_cache: true
    name:
      - rsync
      - jq
      - docker-ce
      - python-docker-py
      - docker-compose
      - chrony
      - ipvsadm
      - graphviz
    state: present

- name: init docker to create folder /etc/docker
  systemd:
    name: docker
    state: started

- name: distribute docker config
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: reload & restart docker
  systemd:
    name: docker
    daemon_reload: true
    enabled: true
    state: restarted

- name: set sysctl
  sysctl:
    name: '{{ item }}'
    value: '1'
    state: present
    reload: true
  with_items:
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
