- name: create /etc/docker folder
  file:        
    path: /etc/docker
    state: directory
    mode: '0755'

- name: distribute docker config 
  template:                      
    src: daemon.json.j2          
    dest: /etc/docker/daemon.json

- name: yum install docker
  yum:
    disablerepo: '*'
    enablerepo: kubeansible
    update_cache: true
    name:
      - docker-ce
      - chrony
      - ipvsadm
    state: present

- name: reload & restart docker
  systemd:
    name: docker
    daemon_reload: true
    enabled: true
    state: restarted

- name: set sysctl
  sysctl:
    name: '{{ item }}'
    value: '1'
    state: present
    reload: true
  with_items:
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
