- name: Check if docker is installed
  shell: 'systemctl status docker | grep running || echo "not running"'
  register: docker_status

- block:
  - name: prepare
    include_tasks: prepare.yml
  
  - name: install docker 
    include_tasks: docker.yml
  when: '"active" not in docker_status.stdout'
