- name: check environment
  script: scripts/check_environment.sh
  register: check_env_output
  environment:
    BREEZE_LSB_ID: "{{ ansible_facts.distribution }}"
    BREEZE_LSB_RELEASE: "{{ ansible_facts.distribution_version }}"
    BREEZE_PYTHON_VERSION: "{{ ansible_facts.python_version }}" 

- name: exit
  fail:
    msg: "{{ check_env_output.stdout }}"
  when: check_env_output.stdout != "true"
    
- name: get seed ip
  shell:
    echo $SSH_CONNECTION | cut -d " " -f 1
  register: ip

- name: add seed to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: '{{ ip.stdout }} {{ package_repo_server }}'
    marker: '# {mark} KUBEANSIBLE DEPLOY MANAGED BLOCK {{ package_repo_server }}'

- name: add to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: '{{ item.key }} {{ item.value.hostname }}'
    marker: "# {mark} KUBEANSIBLE DEPLOY MANAGED BLOCK {{ item.key }}"
  with_dict: "{{ hostvars }}"

- name: check docker
  script: scripts/check_docker.sh {{ harbor }}
  register: check_output

- name: setup docker on all nodes
  include_tasks: docker.yml
  when: check_output.stdout != 'true'
