- name: set hostname
  hostname:
    name: '{{ inventory_hostname }}'
  when: format_hostname

- name: set timezone
  shell: timedatectl set-timezone {{ timezone }}
  when: timezone is defined

- name: start firewalld
  systemd:
    name: firewalld
    enabled: true
    state: started

- name: config firewalld trusted all
  shell: |
    firewall-cmd --set-default-zone=trusted
    firewall-cmd --complete-reload

- name: distribute yum repo
  yum_repository:
    name: kubeansible
    description: kubeansible Repository
    baseurl: "{{ docker_yum_repo }}"
    enabled: yes
    gpgcheck: no
    state: present

- name: distribute chrony server config for Redhat/CentOS
  template:
    src: chrony-server.conf.j2
    dest: /etc/chrony.conf
  when:
  - inventory_hostname == ansible_play_batch[0]

- name: distribute chrony client config for Redhat/CentOS
  template:
    src: chrony-client.conf.j2
    dest: /etc/chrony.conf
  when:
  - inventory_hostname != ansible_play_batch[0]

- name: start chrony for Redhat/CentOS
  systemd:
    name: chronyd
    daemon_reload: true
    enabled: yes
    state: restarted

- name: get yum repo server ip
  shell:
    echo $SSH_CONNECTION | cut -d " " -f 1
  register: ip

- name: add yum repo seed host to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: '{{ ip.stdout }} kubeansible'
    marker: '# {mark} KUBEANSIBLE DEPLOY MANAGED BLOCK kubeansible'

- name: update /etc/hosts file
  become: true
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'hosts.j2') }}"
    state: present
