- name: make harbor dir
  file:
    path: '{{ DPATH }}'
    state: directory
    mode: 0755

- name: unarchive harbor
  unarchive:
    src: '{{ PKG_PATH }}/harbor-offline-installer-{{ harbor_version }}.tgz'
    dest: '{{ DPATH }}'

- name: generate harbor config
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - { src: 'templates/harbor.yml.j2', dest: '{{ DPATH }}/harbor/harbor.yml' }

- name: install docker-compose
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0755
  with_items:
  - { src: '{{ PKG_PATH }}/docker-compose', dest: '/usr/bin/docker-compose' }

- name: launch harbor
  shell: ./install.sh --with-clair --with-chartmuseum
  args:
    chdir: '{{ DPATH }}/harbor'
