- name: create harbor dir
  file:
    path: /data
    state: directory
    mode: 0755

- name: Check if harbor is installed
  command: ls /data
  register: result

- block:
  - name: install docker-compose
    copy:
      src: '{{ base_dir }}/bin/docker-compose'
      dest: /usr/bin/docker-compose
      mode: 0755

  - name: unarchive harbor
    unarchive:
      src: '{{ base_dir }}/file/harbor-offline-installer-{{ harbor_version }}.tgz'
      dest: /data
  
  - name: generate harbor config
    template:
      src: harbor.yml.j2
      dest: /data/harbor/harbor.yml
  
  - name: launch harbor
    shell: ./install.sh --with-clair --with-chartmuseum
    args:
      chdir: /data/harbor
  when: '"registry" not in result.stdout'
